### ISSUE TITLE
site search issue on server of server

### ISSUE THREAD

**Issue by Ran-n** [kaiiiz/hugo-theme-monochrome#29] opened 2022-05-11 21:13 UTC
I have a particular issue and its that i have a server in my github base url that just links to various servers that are on other repositories.
The problem comes when i try to search on any of those other servers, when i do only the results for the base one are available (and the other servers have the site search enabled).

For a more hands on example, you can go to [https://ran-n.github.io/subs/](https://ran-n.github.io/subs/) and you can see how it only searches on the pages available for the server located in [https://ran-n.github.io/](https://ran-n.github.io/).

Obviously, the search functions perpectly when used on a local production server.

**Comment by kaiiiz** [comment] 2022-06-02 09:16
After doing some testing, I found the issue is related to `relativeURLs` and `canonifyURLs` in your config. The current implementation of retrieving the URL of the index file is using the `relLangURL` function provided by hugo. However, `relLangURL` behaves unnormal and doesn't respect the `baseURL` setting if one of the above options is enabled.

It seems that using `absLangURL` doesn't encounter this issue so maybe a quick fix is to change the index retrieving process from `relLangURL` to `absLangURL`. I also consider replacing all of the `relURL` with `absURL` as I didn't notice such a problem before.

**Comment by kaiiiz** [comment] 2023-07-23 15:26
Fixed in v2.0.0.

**Closed as completed by kaiiiz** 2023-07-23 15:26 UTC
Labels: bug
